package ru.bogdanov.guselnik.item

import ru.bogdanov.guselnik.R

enum class Ingredient(val type: String, val label: String, val image: Int? = null, val isInstrument: Boolean=false, val sound:Int?=null){
    AXE("axe", "Топор"),
    KNIFE("knife","Нож"),
    CHISEL("chisel","Долото"),
    FOREST("forest", "Лес"),
    BONFIRE("bonfire", "Костер"),


    BALALAYKA("balalayka","Балалайка",isInstrument = true, sound = R.raw.balalayka, image = R.drawable.z_balalaika),
    BANDURA("bandura","Бандура", isInstrument = true),
    BARABAN("baraban","Барабан",isInstrument = true),
    BARABANKA("barabanka","Барабанка", isInstrument = true, image = R.drawable.z_barabanka),
    BERESTA("beresta","Береста"),
    BILO("bilo","Било",isInstrument = true, image = R.drawable.z_bilo),
    BOTALO("botalo","Ботало", isInstrument = true),
    BRELKA("brelka","Брёлка", isInstrument = true),
    BRUNCHALKA("brunchalka","Брунчалка", isInstrument = true),
    BRYACALO("bryacalo","Бряцало",isInstrument = true),
    BUBEN("buben","Бубен", isInstrument = true),
    CIMBALI("cimbali","Цимбалы",isInstrument = true),
    DEKA("deka", "Дэка"),
    DEKA_S_OTVERSTIAYAMI("deka_holed","Дека с отверстиями"),
    DOMRA("domra","Домра", isInstrument = true),
    DOSKA("doska", "Доска"),
    DOSKA_HOLED("doska_holed","Доска с дырками"),
    DROVA("drova","Дрова"),
    FUYARA("fuyara","Фуяра", isInstrument = true),
    GALEYKA_DVOYNAYA("galeyka_double","Двойная жалейка", isInstrument = true),
    GARMON_HROMKA("garmon_hromka", "Гармонь хромка",isInstrument = true),
    GARMON_SARATOV("garmon_saratov", "Гармонь саратовская", isInstrument = true),
    GARMONIKA("garmonika", "Гармоника", isInstrument = true),
    GILA("gila","Жила"),
    GLINA("glina","Глина"),
    GREBEN("greben","Гребень",isInstrument = true),
    GRIF("grif","Гриф"),
    GUDOK("gudok","Гудок", isInstrument = true),
    GUSACHOK("gusachok","Гусачок", isInstrument = true),
    GUSLI_KRIL("gusli_kril","Гусли крыловидные",isInstrument = true, sound = R.raw.gusli1, image = R.drawable.z_gusli_krilovidnie),
    GUSLI_LIROOBR("gusli_liroobr","Гусли лирообразные",isInstrument = true),
    GUSLI_PSALTIR("gusli_psaltir","Гусли псалтырь", isInstrument = true),
    KALUKA("kaluka","Калюка",isInstrument = true, sound = R.raw.kaluka, image = R.drawable.z_kalyuka),
    KAPKAN("kapkan", "Капкан"),
    KOBZA("kobza","Кобза", isInstrument = true),
    KOGA("koga","Кожа"),
    KOLESNAYA_LIRA("kolesnaya_lira", "Колесная лира", isInstrument = true),
    KOLESO("koleso", "Колесо"),
    KOLOKOLCHIK("kolokolchik","Колокольчик",isInstrument = true),
    KOLOTUSHKA("kolotushka","Колотушка", isInstrument = true),
    KOPIE("kopie", "Копье"),
    KORITSE("koritse","Корытце"),
    KORITSE_S_OKNOM("koritse_window","Корытце с окном"),
    KORITSE_VODA("koritse_voda","Корытце с водой"),
    KORPUS("korpus","Корпус"),
    KORPUS_HOLED("korpus_holed","Корпус с отверстием"),
    KORPUS_WINDOW("korpus_window","Корпус с окном"),
    KOSA("kosa","Коса", isInstrument = true),
    KOST("kost","Кость"),
    KRICA("krica", "Крица"),
    KUKIGL("kukigl","Кукиглы",isInstrument = true),
    LITIE("litie","Литье"),
    LOPATA("lopata", "Лопата"),
    LUK("luk", "Лук"),
    MEHA("meha", "Меха"),
    NEREHT_ROGOK("nereht_rogok", "Нерехтинский рожок", isInstrument = true),
    OGERELOK("oregelok","Ожерелок", isInstrument = true),
    PALKA("palka", "Палка"),
    PERO("pero", "Перо"),
    PISHIK("pishik","Пищик", isInstrument = true),
    POKOVKA("pokovka","Поковка"),
    POLENO("poleno", "Полено"),
    POSVISTEL("posvistel","Посвистель", isInstrument = true),
    PROBKA("probka","Пробка-пыж"),
    RASPLAV("rasplav","Расплав"),
    ROG("rog", "Рог"),
    ROG_SIGNALNIY("rog_signakniy", "Рог сигнальный", isInstrument = true),
    RUBEL("rubel","Рубель", isInstrument = true),
    SHANKUNOK("sharkunok","Шаркунок", isInstrument = true),
    SHEPKA("shepka","Щепка"),
    SHKURA("shkura", "Шкура"),
    SILKI("silki", "Силки"),
    SKRIPKA_NARODNAYA("skripka_nar","Скрипка народная", isInstrument = true),
    SMYK("smyk","Смык"),
    SOPEL("sopel","Сопель", isInstrument = true),
    SPOON("spoon", "Ложка"),
    SPOONS("spoons", "Ложки", isInstrument = true, sound = R.raw.logki),
    STRUNA("struna","Струна"),
    SURNA("surna","Сурна", isInstrument = true),
    SVISTULKA("svistulka","Свистулька", isInstrument = true),
    SWIREL_DWOY("swirel_dwoy","Свирель двойчатка", isInstrument = true),
    TRESHETKA("treshetka","Трещетка",isInstrument = true),
    TROSTNIK("trostnik","Тростник"),
    TRUBA_PAST("truba_past", "Труба пастушечья", isInstrument = true),
    TRUBKA("trubka", "Трубка"),
    TRUBKA_S_OTVERSTIAYAMI("trubka_holed", "Трубка с отверстиями"),
    VARGAN("vargan","Варган", isInstrument = true),
    VETROVIK("vetrovik","Ветровик", isInstrument = true),
    VOLINKA("volinka", "Волынка",isInstrument = true),
    VOLOS("volos", "Волос"),
    YAZICHOK("yazichok", "Язычок"),
    YAZUCHEK_METAL("yaz_met","Язычок из металла"),
    ZEMLYA("zemlya", "Земля"),
    ZVENIASHIE_PRIVESI("zvi_pri","Звинящие привесы", isInstrument = true);

    override fun toString(): String {
        return type
    }
}

fun getIngredientByType(type:String):Ingredient?{
    val ingr=Ingredient.values().find { it.type==type }
    return ingr
}