package ru.bogdanov.guselnik.item

import ru.bogdanov.guselnik.R

enum class Ingredient(val type: String, val label: String, val image: Int? = null, val isInstrument: Boolean=false, val sound:Int?=null){
    AXE("axe", "Топор"),
    KNIFE("knife","Нож"),
    CHISEL("chisel","Долото"),
    FOREST("forest", "Лес"),
    BONFIRE("bonfire", "Костер"),


    BALALAYKA("balalayka","Балалайка",isInstrument = true, sound = R.raw.balalayka, image = R.drawable.balalayka),
    BANDURA("bandura","Бандура", isInstrument = true, image = R.drawable.bandura ),
    BARABAN("baraban","Барабан",isInstrument = true, image = R.drawable.baraban ),
    BARABANKA("barabanka","Барабанка", isInstrument = true, image = R.drawable.barabanka ),
    BERESTA("beresta","Береста", image = R.drawable.beresta ),
    BILO("bilo","Било",isInstrument = true, image = R.drawable.bilo ),
    BOTALO("botalo","Ботало", isInstrument = true, image = R.drawable.botalo ),
    BRELKA("brelka","Брёлка", isInstrument = true, image = R.drawable.brelka ),
    BRUNCHALKA("brunchalka","Брунчалка", isInstrument = true, image = R.drawable.brunchalka ),
    BRYACALO("bryacalo","Бряцало",isInstrument = true, image = R.drawable.bryatsalo ),
    BUBEN("buben","Бубен", isInstrument = true, image = R.drawable.buben ),
    CIMBALI("cimbali","Цимбалы",isInstrument = true, image = R.drawable.tsimbaly ),
    DEKA("deka", "Дэка", image = R.drawable.deka ),
    DEKA_S_OTVERSTIAYAMI("deka_holed","Дека с отверстиями", image = R.drawable.deka_s_otverstiem ),
    DOMRA("domra","Домра", isInstrument = true, image = R.drawable.domra ),
    DOSKA("doska", "Доска", image = R.drawable. doska),
    DOSKA_HOLED("doska_holed","Доска с дырками", image = R.drawable.deka_s_otverstiem ),
    DROVA("drova","Дрова", image = R.drawable.drova),
    FUYARA("fuyara","Фуяра", isInstrument = true, image = R.drawable.fuyara ),
    GALEYKA_DVOYNAYA("galeyka_double","Двойная жалейка", isInstrument = true, image = R.drawable.dvoynaya_zhaleyka ),
    GARMON_HROMKA("garmon_hromka", "Гармонь хромка",isInstrument = true, image = R.drawable.garmon_khromka ),
    GARMON_SARATOV("garmon_saratov", "Гармонь саратовская", isInstrument = true, image = R.drawable.garmon_saratovskaya ),
    GARMONIKA("garmonika", "Гармоника", isInstrument = true, image = R.drawable.garmonika ),
    GILA("gila","Жила", image = R.drawable.zhila ),
    GLINA("glina","Глина", image = R.drawable.glina ),
    GREBEN("greben","Гребень",isInstrument = true, image = R.drawable.greben ),
    GRIF("grif","Гриф", image = R.drawable.grif ),
    GUDOK("gudok","Гудок", isInstrument = true, image = R.drawable.gudok ),
    GUSACHOK("gusachok","Гусачок", isInstrument = true, image = R.drawable.gusachok ),
    GUSLI_KRIL("gusli_kril","Гусли крыловидные",isInstrument = true, sound = R.raw.gusli1, image = R.drawable.gusli_krylovidnye ),
    GUSLI_LIROOBR("gusli_liroobr","Гусли лирообразные",isInstrument = true, image = R.drawable.gusli_liroobraznye ),
    GUSLI_PSALTIR("gusli_psaltir","Гусли псалтырь", isInstrument = true, image = R.drawable.gusli_psaltir ),
    KALUKA("kaluka","Калюка",isInstrument = true, sound = R.raw.kaluka,  image = R.drawable.kalyuka ),
    KAPKAN("kapkan", "Капкан", image = R.drawable.kapkan ),
    KOBZA("kobza","Кобза", isInstrument = true, image = R.drawable.kobza ),
    KOGA("koga","Кожа", image = R.drawable.kozha),
    KOLESNAYA_LIRA("kolesnaya_lira", "Колесная лира", isInstrument = true, image = R.drawable.kolesnaya_lira),
    KOLESO("koleso", "Колесо", image = R.drawable.koleso),
    KOLOKOLCHIK("kolokolchik","Колокольчик",isInstrument = true, image = R.drawable.kolokolchik),
    KOLOTUSHKA("kolotushka","Колотушка", isInstrument = true, image = R.drawable.kolotushka),
    KOPIE("kopie", "Копье", image = R.drawable.kopye),
    KORITSE("koritse","Корытце", image = R.drawable.koryttse),
    KORITSE_S_OKNOM("koritse_window","Корытце с окном", image = R.drawable.koryttse_s_oknom),
    KORITSE_VODA("koritse_voda","Корытце с водой", image = R.drawable.koryttse_s_vodoy),
    KORPUS("korpus","Корпус", image = R.drawable.korpus),
    KORPUS_HOLED("korpus_holed","Корпус с отверстием", image = R.drawable.korpus_s_otverstiem),
    KORPUS_WINDOW("korpus_window","Корпус с окном", image = R.drawable.koryttse_s_oknom),
    KOSA("kosa","Коса", isInstrument = true, image = R.drawable.kosa),
    KOST("kost","Кость", image = R.drawable.kost),
    KRICA("krica", "Крица", image = R.drawable.kritsa),
    KUKIGL("kukigl","Кукиглы",isInstrument = true, image = R.drawable.kugikly),
    LOPATA("lopata", "Лопата", image = R.drawable.lopata),
    LUK("luk", "Лук", image = R.drawable.luk),
    MEHA("meha", "Меха", image = R.drawable.mekha),
    NEREHT_ROGOK("nereht_rogok", "Нерехтинский рожок", isInstrument = true, image = R.drawable.nerekhtskiy_rozhok),
    OGERELOK("oregelok","Ожерелок", isInstrument = true, image = R.drawable.ozherelok),
    PALKA("palka", "Палка", image = R.drawable.palka),
    PERO("pero", "Перо", image = R.drawable.pero),
    PISHIK("pishik","Пищик", isInstrument = true, image = R.drawable.pishchik),
    POKOVKA("pokovka","Поковка", image = R.drawable.pokovka),
    POLENO("poleno", "Полено", image = R.drawable.brevno),
    POSVISTEL("posvistel","Посвистель", isInstrument = true, image = R.drawable.posvistel),
    PROBKA("probka","Пробка-пыж", image = R.drawable.probka_pyzh),
    RASPLAV("rasplav","Расплав", image = R.drawable.rasplav),
    ROG("rog", "Рог", image = R.drawable.rog),
    ROG_SIGNALNIY("rog_signakniy", "Рог сигнальный", isInstrument = true, image = R.drawable.rog_signalnyy),
    RUBEL("rubel","Рубель", isInstrument = true, image = R.drawable.rubel),
    SHANKUNOK("sharkunok","Шаркунок", isInstrument = true, image = R.drawable.sharkunok),
    SHEPKA("shepka","Щепка", image = R.drawable.shchepka),
    SHKURA("shkura", "Шкура", image = R.drawable.shkura),
    SILKI("silki", "Силки", image = R.drawable.silki),
    SKRIPKA_NARODNAYA("skripka_nar","Скрипка народная", isInstrument = true, image = R.drawable.skripka_narodnaya),
    SMYK("smyk","Смык", image = R.drawable.smyk),
    SOPEL("sopel","Сопель", isInstrument = true, image = R.drawable.sopel),
    SPOON("spoon", "Ложка", image = R.drawable.lozhka),
    SPOONS("spoons", "Ложки", isInstrument = true, sound = R.raw.logki, image = R.drawable.lozhki),
    STRUNA("struna","Струна", image = R.drawable.struna),
    SURNA("surna","Сурна", isInstrument = true, image = R.drawable.surna),
    SVISTULKA("svistulka","Свистулька", isInstrument = true, image = R.drawable.svistulka),
    SWIREL_DWOY("swirel_dwoy","Свирель двойчатка", isInstrument = true, image = R.drawable.svirel_dvoychatka),
    TRESHETKA("treshetka","Трещетка",isInstrument = true, image = R.drawable.treshchotka),
    TROSTNIK("trostnik","Тростник", image = R.drawable.trostnik),
    TRUBA_PAST("truba_past", "Труба пастушечья", isInstrument = true, image = R.drawable.truba_pastusheskaya),
    TRUBKA("trubka", "Трубка", image = R.drawable.trubka),
    TRUBKA_S_OTVERSTIAYAMI("trubka_holed", "Трубка с отверстиями", image = R.drawable.trubka_s_otverstiyami),
    VARGAN("vargan","Варган", isInstrument = true, image = R.drawable.vargan),
    VETROVIK("vetrovik","Ветровик", isInstrument = true, image = R.drawable.vetrovik),
    VOLINKA("volinka", "Волынка",isInstrument = true, image = R.drawable.volynka),
    VOLOS("volos", "Волос", image = R.drawable.volos),
    YAZICHOK("yazichok", "Язычок", image = R.drawable.yazychok),
    YAZUCHEK_METAL("yaz_met","Язычок из металла", image = R.drawable.yazychok_iz_metalla),
    ZEMLYA("zemlya", "Земля", image = R.drawable.zemlya),
    ZVENIASHIE_PRIVESI("zvi_pri","Звинящие привесы", isInstrument = true, image = R.drawable.zvenyashchie_privesy);

    override fun toString(): String {
        return type
    }
}

fun getIngredientByType(type:String):Ingredient?{
    val ingr=Ingredient.values().find { it.type==type }
    return ingr
}