package ru.bogdanov.guselnik.item

enum class Ingredient(val type: String, val label: String, val image: Int? = null, val isInstrument: Boolean=false){
    POLENO("poleno", "Полено"),
    TROSTNIK("trostnik","Тростник"),
    BERESTA("beresta","Береста"),

    PALKA("palka", "Палка"),

    SPOON("spoon", "Ложка"),

    SPOONS("spoons", "Ложки", isInstrument = true),
    SHANKUNOK("sharkunok","Шаркунок", isInstrument = true),
    TRESHETKA("treshetka","Трещетка",isInstrument = true),
    SHEPKA("shepka","Щепка"),
    RUBEL("rubel","Рубель", isInstrument = true),
    VETROVIK("vetrovik","Ветровик", isInstrument = true),
    GREBEN("greben","Гребень",isInstrument = true),
    BARABANKA("barabanka","Барабанка", isInstrument = true),
    DOSKA_HOLED("doska_holed","Доска с дырками"),
    KOSA("kosa","Коса", isInstrument = true),
    POKOVKA("pokovka","Поковка"),
    VARGAN("vargan","Варган", isInstrument = true),
    YAZUCHEK_METAL("yaz_met","Язычок из металла"),
    GUSACHOK("gusachok","Гусачок", isInstrument = true),
    SMYK("smyk","Смык"),
    BARABAN("baraban","Барабан",isInstrument = true),
    BRUNCHALKA("brunchalka","Брунчалка", isInstrument = true),
    KOST("kost","Кость"),
    GILA("gila","Жила"),
    ZVENIASHIE_PRIVESI("zvi_pri","Звинящие привесы", isInstrument = true),
    LITIE("litie","Литье"),
    KORITSE_VODA("koritse_voda","Корытце с водой"),
    DROVA("drova","Дрова"),
    KOLOTUSHKA("kolotushka","Колотушка", isInstrument = true),
    KORPUS("korpus","Корпус"),
    BUBEN("buben","Бубен", isInstrument = true),
    KOLOKOLCHIK("kolokolchik","Колокольчик",isInstrument = true),
    KORITSE("koritse","Корытце",isInstrument = true),
    KOGA("koga","Кожа"),
    RASPLAV("rasplav","Расплав"),
    GLINA("glina","Глина"),
    BRYACALO("bryacalo","Бряцало",isInstrument = true),
    BOTALO("botalo","Ботало", isInstrument = true),
    OGERELOK("oregelok","Ожерелок", isInstrument = true),
    BILO("bilo","Било",isInstrument = true),
    GUSLI_LIROOBR("gusli_liroobr","Гусли лирообразные",isInstrument = true),
    KORPUS_WINDOW("korpus_window","Корпус с окном"),
    STRUNA("struna","Струна"),
    GUSLI_KRIL("gusli_kril","Гусли крыловидные",isInstrument = true),
    GUSLI_PSALTIR("gusli_psaltir","Гусли псалтырь", isInstrument = true),
    CIMBALI("cimbali","Цимбалы",isInstrument = true),
    BANDURA("bandura","Бандура", isInstrument = true),
    GRIF("grif","Гриф"),
    BALALAYKA("balalayka","Балалайка",isInstrument = true),
    KORPUS_HOLED("korpus_holed","Корпус с отверстием"),
    DOMRA("domra","Домра", isInstrument = true),
    GUDOK("gudok","Гудок", isInstrument = true),
    SKRIPKA_NARODNAYA("skripka_nar","Скрипка народная", isInstrument = true),
    KUKIGL("kukigl","Кукиглы",isInstrument = true),
    KALUKA("kaluka","Калюка",isInstrument = true),
    SOPEL("sopel","Сопель", isInstrument = true),
    SWIREL_DWOY("swirel_dwoy","Свирель двойчатка", isInstrument = true),
    SVISTULKA("svistulka","Свистулька", isInstrument = true),
    POSVISTEL("posvistel","Посвистель", isInstrument = true),
    PISHIK("pishik","Пищик", isInstrument = true),
    GALEYKA("galeyka","Жалейка", isInstrument = true),
    SURNA("surna","Сурна", isInstrument = true),
    YAZICHOK("yazichok", "Язычок"),
    NEREHT_ROGOK("nereht_rogok", "Нерехтинский рожок", isInstrument = true),
    VOLINKA("volinka", "Волынка",isInstrument = true),
    SHKURA("shkura", "Шкура"),
    ROG_SIGNALNIY("rog_signakniy", "Рог сигнальный", isInstrument = true),
    ROG("rog", "Рог"),
    TRUBA_PAST("truba_past", "Труба пастушечья", isInstrument = true),
    TRUBKA("trubka", "Трубка"),
    KOLESNAYA_LIRA("kolesnaya_lira", "Колесная лира", isInstrument = true),
    KOLESO("koleso", "Колесо"),
    GARMONIKA("garmonika", "Гармоника", isInstrument = true),
    GARMON_HROMKA("garmon_hromka", "Гармонь хромка",isInstrument = true),
    MEHA("meha", "Меха"),
    GARMON_SARATOV("garmon_saratov", "Гармонь саратовская", isInstrument = true),

    DOSKA("doska", "Доска"),
    KRICA("krica", "Крица"),
    DEKA("deka", "Дэка"),
    LOPATA("lopata", "Лопата"),
    KOPIE("kopie", "Копье"),
    KAPKAN("kapkan", "Капкан"),
    LUK("luk", "Лук"),
    SILKI("silki", "Силки"),
    PERO("pero", "Перо"),
    ZEMLYA("zemlya", "Земля"),
    VOLOS("volos", "Волос");

    override fun toString(): String {
        return type
    }
}