package ru.bogdanov.guselnik.item

sealed class Instruments(tag:String, name:String, image:Int?=null){
    class Crackle():Instruments("crackle", "трещетка")
    class Drum():Instruments("drum", "барабанка")
    class Firewood():Instruments("firewood", "дрова")
    class Kukigl():Instruments("kukigl", "кугиклы")
    class Kaluka():Instruments("kaluka", "калюка")
    class Whistle():Instruments("whistle", "свирель")
    class WhistleDouble():Instruments("whistleDouble", "свирель двойчатка")
    class Pishik():Instruments("pishik", "пищик")
    class PishikDouble():Instruments("pishikDouble", "двойной пищик")
    class KurskWhistle():Instruments("kurskWhistle", "курский рожок")
    class NerehtWhistle():Instruments("nerehtWhistle", "нерехтский рожек")
    class ShepherdWhistle():Instruments("shepherdWhistle", "постушеская труба")
    class Sharkunok():Instruments("sharkunok", "шаркунок")
    class Rubel():Instruments("rubel", "рубель")
    class Spoons():Instruments("spoons", "ложки")
    class GusliLir():Instruments("gusliLir", "гусли лирообразные")
    class Balalayka():Instruments("balalayka", "балалайка")
    class Gudok():Instruments("gudok", "gudok")
    class Violin():Instruments("violin", "скрипка")
    class WheeledLyra():Instruments("wheeledLyra", "колесная лира")
    class Greben():Instruments("greben", "гребень")
    class Cimbal():Instruments("cimbal", "цимбалы")
    class GusliKril():Instruments("gusliKril", "гусли крыловидные")
}

sealed class Ingredients(tag:String, name:String, image:Int?=null) {
    class Log():Ingredients("log", "полено")
    class Cane():Ingredients("cane", "тростник")
    class Bark():Ingredients("bark", "кора")
    class Plank():Ingredients("plank", "доска")
    class Sliver():Ingredients("sliver", "щепка")
    class Peg():Ingredients("peg", "колок")
    class Stick():Ingredients("stick", "палка")
    class Neck():Ingredients("neck", "гриф")
    class Tube():Ingredients("tube", "трубка")
    class TubeHoled():Ingredients("tubeHoled", "трубка с отверстиями")
    class Deck():Ingredients("deck", "дека")
    class DeckHoled():Ingredients("deckHoled", "дека с дырками")
    class PlankHoled():Ingredients("plankHoled", "доска с отверстиями")
    class Wheel():Ingredients("wheel", "колесо")
    class WheelLyra():Ingredients("wheelLyra", "колесо для лиры")
    class Trough():Ingredients("trough", "корыто")
    class TroughWindow():Ingredients("troughWindow", "корыто с окном")
    class Body():Ingredients("body", "корпус")
    class BodyHoled():Ingredients("bodyHoled", "корпус с отверстиями")
    class BodyWindow():Ingredients("bodyWindow", "корпус с окном")
    class Tongue():Ingredients("tongue", "язычок")
    class Resin():Ingredients("resin", "смола")
    class Bow():Ingredients("bow", "смык")
    class Spoon():Ingredients("spoon", "ложка")
}