package ru.bogdanov.guselnik.item

interface RecipeItem

sealed class Instrument(val tag: String, val name: String, val image: Int? = null) : RecipeItem {
    class Crackle() : Instrument("crackle", "трещетка")
    class Drum() : Instrument("drum", "барабанка")
    class Firewood() : Instrument("firewood", "дрова")
    class Kukigl() : Instrument("kukigl", "кугиклы")
    class Kaluka() : Instrument("kaluka", "калюка")
    class Whistle() : Instrument("whistle", "свирель")
    class WhistleDouble() : Instrument("whistleDouble", "свирель двойчатка")
    class Pishik() : Instrument("pishik", "пищик")
    class PishikDouble() : Instrument("pishikDouble", "двойной пищик")
    class KurskWhistle() : Instrument("kurskWhistle", "курский рожок")
    class NerehtWhistle() : Instrument("nerehtWhistle", "нерехтский рожек")
    class ShepherdWhistle() : Instrument("shepherdWhistle", "постушеская труба")
    class Sharkunok() : Instrument("sharkunok", "шаркунок")
    class Rubel() : Instrument("rubel", "рубель")
    class Spoons() : Instrument("spoons", "ложки")
    class GusliLir() : Instrument("gusliLir", "гусли лирообразные")
    class Balalayka() : Instrument("balalayka", "балалайка")
    class Gudok() : Instrument("gudok", "gudok")
    class Violin() : Instrument("violin", "скрипка")
    class WheeledLyra() : Instrument("wheeledLyra", "колесная лира")
    class Greben() : Instrument("greben", "гребень")
    class Cimbal() : Instrument("cimbal", "цимбалы")
    class GusliKril() : Instrument("gusliKril", "гусли крыловидные")
}

sealed class Ingredient(val tag: String, val name: String, val image: Int? = null) : RecipeItem {
    class Log() : Ingredient("log", "полено")
    class Cane() : Ingredient("cane", "тростник")
    class Bark() : Ingredient("bark", "кора")
    class Plank() : Ingredient("plank", "доска")
    class Sliver() : Ingredient("sliver", "щепка")
    class Peg() : Ingredient("peg", "колок")
    class Stick() : Ingredient("stick", "палка")
    class Neck() : Ingredient("neck", "гриф")
    class Tube() : Ingredient("tube", "трубка")
    class TubeHoled() : Ingredient("tubeHoled", "трубка с отверстиями")
    class Deck() : Ingredient("deck", "дека")
    class DeckHoled() : Ingredient("deckHoled", "дека с дырками")
    class PlankHoled() : Ingredient("plankHoled", "доска с отверстиями")
    class Wheel() : Ingredient("wheel", "колесо")
    class WheelLyra() : Ingredient("wheelLyra", "колесо для лиры")
    class Trough() : Ingredient("trough", "корыто")
    class TroughWindow() : Ingredient("troughWindow", "корыто с окном")
    class Body() : Ingredient("body", "корпус")
    class BodyHoled() : Ingredient("bodyHoled", "корпус с отверстиями")
    class BodyWindow() : Ingredient("bodyWindow", "корпус с окном")
    class Tongue() : Ingredient("tongue", "язычок")
    class Resin() : Ingredient("resin", "смола")
    class Bow() : Ingredient("bow", "смык")
    class Spoon() : Ingredient("spoon", "ложка")
}